mappings:
  DocumentationOpenSearchController: SilverStripe\DocsViewer\Controllers\DocumentationOpenSearchController
  DocumentationViewer: SilverStripe\DocsViewer\Controllers\DocumentationViewer
  DocumentationSearchExtension: SilverStripe\DocsViewer\Extensions\DocumentationSearchExtension
  DocumentationStaticPublisherExtension: SilverStripe\DocsViewer\Extensions\DocumentationStaticPublisherExtension
  DocumentationViewerVersionWarning: SilverStripe\DocsViewer\Extensions\DocumentationViewerVersionWarning
  DocumentationAdvancedSearchForm: SilverStripe\DocsViewer\Forms\DocumentationAdvancedSearchForm
  DocumentationSearchForm: SilverStripe\DocsViewer\Forms\DocumentationSearchForm
  DocumentationEntity: SilverStripe\DocsViewer\Models\DocumentationEntity
  DocumentationFolder: SilverStripe\DocsViewer\Models\DocumentationFolder
  DocumentationPage: SilverStripe\DocsViewer\Models\DocumentationPage
  CheckDocsSourcesTask: SilverStripe\DocsViewer\Tasks\CheckDocsSourcesTask
  DocumentationBuild: SilverStripe\DocsViewer\Tasks\DocumentationBuild
  RebuildLuceneDocsIndex: SilverStripe\DocsViewer\Tasks\RebuildLuceneDocsIndex
  DocumentationHelper: SilverStripe\DocsViewer\DocumentationHelper
  DocumentationManifest: SilverStripe\DocsViewer\DocumentationManifest
  DocumentationManifestFileFinder: SilverStripe\DocsViewer\DocumentationManifestFileFinder
  DocumentationParser: SilverStripe\DocsViewer\DocumentationParser
  DocumentationPermalinks: SilverStripe\DocsViewer\DocumentationPermalinks
  DocumentationSearch: SilverStripe\DocsViewer\DocumentationSearch
  DocumentationEntityTest: SilverStripe\DocsViewer\Tests\DocumentationEntityTest
  DocumentationHelperTests: SilverStripe\DocsViewer\Tests\DocumentationHelperTests
  DocumentationManifestTests: SilverStripe\DocsViewer\Tests\DocumentationManifestTests
  DocumentationPageTest: SilverStripe\DocsViewer\Tests\DocumentationPageTest
  DocumentationParserTest: SilverStripe\DocsViewer\Tests\DocumentationParserTest
  DocumentationPermalinksTest: SilverStripe\DocsViewer\Tests\DocumentationPermalinksTest
  DocumentationSearchTest: SilverStripe\DocsViewer\Tests\DocumentationSearchTest
  DocumentationViewerTest: SilverStripe\DocsViewer\Tests\DocumentationViewerTest
  DocumentationViewerVersionWarningTest: SilverStripe\DocsViewer\Tests\DocumentationViewerVersionWarningTest
